name: DataflowEXP_Workflow
on:
  pull_request:
  push:
    branches:
     - feature/poc_sqlexp
     - poc_sqlexp
   
jobs:
  dataflow-job:
   runs-on: ubuntu-latest
   defaults:
     run:
      shell: bash
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
      
  dataflow-push: 
    needs: dataflow-job
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        directory: [SQL-files]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
           
    - name: Detect file diff
      run: |
         echo "Listing modified files from the last commit:"
         git diff HEAD~1 --name-only --diff-filter=MA --output=diff.txt SQL-files
         cat diff.txt
         echo `cat diff.txt`
