name: DataflowEXP_Workflow
on:
  push:
    branches:
    - 'feature/poc_dfexp'
    #- '!development'
    #- '!release/**'
    # - '!master'
    #- '!hotfix/**'
  pull_request:
    branches:
    - 'poc_dfexp'
   # - 'development'
   # - 'release/**'
   # - 'master'
   # - 'hotfix/**'
    types: 
    - closed
    
    jobs:
      name: checkout-job
      runs-on: ubuntu-latest
      defaults:
        run:
        shell: bash
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      name: check-job
       needs: checkout-job
       runs-on: ubuntu-latest
       strategy:
        matrix: 
          directory: [dataflow/templates]
       steps:
       - name: Checkout code
         uses: actions/checkout@v2
         with:
           fetch-depth: 2
           
       - name: Detect file diff
      run: |
        echo "Listing modified files from the last commit:"
        git diff HEAD~1 --name-only --diff-filter=MA --output=diff.txt dataflow/templates/
        cat diff.txt
        echo `cat diff.txt`
        
        
      

       
     
  
