name: DataflowEXP_Workflow
on:
  push:
    branches:
    - 'feature/poc_dfexp'
    #- '!development'
    #- '!release/**'
    # - '!master'
    #- '!hotfix/**'
  pull_request:
    branches:
    - 'poc_dfexp'
   # - 'development'
   # - 'release/**'
   # - 'master'
   # - 'hotfix/**'
    types: 
    - closed
   
jobs:
  name: dataflow-job
   runs-on: ubuntu-latest
   defaults:
     run:
      shell: bash
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
      
  name: dataflow-push
    needs: dataflow-job
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        directory: [dataflow/templates]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
           
    - name: Detect file diff
      run: |
         echo "Listing modified files from the last commit:"
         #git diff HEAD~1 --name-only --diff-filter=MA --output=diff.txt dataflow/templates/
         git diff --dirstat=files,0 HEAD~1 | sed 's/^[ 0-9.]\+% //g'
         #cat diff.txt
         #echo `cat diff.txt`
        
        
      

       
     
  
